// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/grpcplay/pb/library.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcplay_pb_library_proto_rawDescGZIP(), []int{0}
}

func (x *BookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_internal_grpcplay_pb_library_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Book) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpcplay_pb_library_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type UploadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSummary) Reset() {
	*x = UploadSummary{}
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSummary) ProtoMessage() {}

func (x *UploadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSummary.ProtoReflect.Descriptor instead.
func (*UploadSummary) Descriptor() ([]byte, []int) {
	return file_internal_grpcplay_pb_library_proto_rawDescGZIP(), []int{3}
}

func (x *UploadSummary) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *UploadSummary) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpcplay_pb_library_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpcplay_pb_library_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_internal_grpcplay_pb_library_proto protoreflect.FileDescriptor

const file_internal_grpcplay_pb_library_proto_rawDesc = "" +
	"\n" +
	"\"internal/grpcplay/pb/library.proto\x12\alibrary\"\x1d\n" +
	"\vBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"#\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\"G\n" +
	"\rUploadSummary\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x05R\brejected\"5\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text2\xd7\x01\n" +
	"\aLibrary\x12.\n" +
	"\aGetBook\x12\x14.library.BookRequest\x1a\r.library.Book\x121\n" +
	"\x06Search\x12\x16.library.SearchRequest\x1a\r.library.Book0\x01\x121\n" +
	"\x06Upload\x12\r.library.Book\x1a\x16.library.UploadSummary(\x01\x126\n" +
	"\x04Chat\x12\x14.library.ChatMessage\x1a\x14.library.ChatMessage(\x010\x01B!Z\x1fplayground/internal/grpcplay/pbb\x06proto3"

var (
	file_internal_grpcplay_pb_library_proto_rawDescOnce sync.Once
	file_internal_grpcplay_pb_library_proto_rawDescData []byte
)

func file_internal_grpcplay_pb_library_proto_rawDescGZIP() []byte {
	file_internal_grpcplay_pb_library_proto_rawDescOnce.Do(func() {
		file_internal_grpcplay_pb_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpcplay_pb_library_proto_rawDesc), len(file_internal_grpcplay_pb_library_proto_rawDesc)))
	})
	return file_internal_grpcplay_pb_library_proto_rawDescData
}

var file_internal_grpcplay_pb_library_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_grpcplay_pb_library_proto_goTypes = []any{
	(*BookRequest)(nil),   // 0: library.BookRequest
	(*Book)(nil),          // 1: library.Book
	(*SearchRequest)(nil), // 2: library.SearchRequest
	(*UploadSummary)(nil), // 3: library.UploadSummary
	(*ChatMessage)(nil),   // 4: library.ChatMessage
}
var file_internal_grpcplay_pb_library_proto_depIdxs = []int32{
	0, // 0: library.Library.GetBook:input_type -> library.BookRequest
	2, // 1: library.Library.Search:input_type -> library.SearchRequest
	1, // 2: library.Library.Upload:input_type -> library.Book
	4, // 3: library.Library.Chat:input_type -> library.ChatMessage
	1, // 4: library.Library.GetBook:output_type -> library.Book
	1, // 5: library.Library.Search:output_type -> library.Book
	3, // 6: library.Library.Upload:output_type -> library.UploadSummary
	4, // 7: library.Library.Chat:output_type -> library.ChatMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpcplay_pb_library_proto_init() }
func file_internal_grpcplay_pb_library_proto_init() {
	if File_internal_grpcplay_pb_library_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpcplay_pb_library_proto_rawDesc), len(file_internal_grpcplay_pb_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpcplay_pb_library_proto_goTypes,
		DependencyIndexes: file_internal_grpcplay_pb_library_proto_depIdxs,
		MessageInfos:      file_internal_grpcplay_pb_library_proto_msgTypes,
	}.Build()
	File_internal_grpcplay_pb_library_proto = out.File
	file_internal_grpcplay_pb_library_proto_goTypes = nil
	file_internal_grpcplay_pb_library_proto_depIdxs = nil
}
