// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	City pgtype.Text
}

type Book struct {
	ID       int64
	AuthorID int64
	Title    string
	Year     int32
	Tags     []string
}
