// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBook = `-- name: AddBook :one
INSERT INTO books (author_id, title, year, tags) VALUES ($1, $2, $3, $4)
RETURNING id, author_id, title, year, tags
`

type AddBookParams struct {
	AuthorID int64
	Title    string
	Year     int32
	Tags     []string
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, addBook,
		arg.AuthorID,
		arg.Title,
		arg.Year,
		arg.Tags,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Year,
		&i.Tags,
	)
	return i, err
}

const booksByAuthor = `-- name: BooksByAuthor :many
SELECT b.id, b.title, b.year, a.name AS author
FROM books b JOIN authors a ON a.id = b.author_id
WHERE a.name = $1
ORDER BY b.year
`

type BooksByAuthorRow struct {
	ID     int64
	Title  string
	Year   int32
	Author string
}

func (q *Queries) BooksByAuthor(ctx context.Context, name string) ([]BooksByAuthorRow, error) {
	rows, err := q.db.Query(ctx, booksByAuthor, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BooksByAuthorRow
	for rows.Next() {
		var i BooksByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBooksPerCity = `-- name: CountBooksPerCity :many
SELECT a.city, count(*) AS books
FROM books b JOIN authors a ON a.id = b.author_id
GROUP BY a.city
ORDER BY books DESC
`

type CountBooksPerCityRow struct {
	City  pgtype.Text
	Books int64
}

func (q *Queries) CountBooksPerCity(ctx context.Context) ([]CountBooksPerCityRow, error) {
	rows, err := q.db.Query(ctx, countBooksPerCity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBooksPerCityRow
	for rows.Next() {
		var i CountBooksPerCityRow
		if err := rows.Scan(&i.City, &i.Books); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, city) VALUES ($1, $2)
RETURNING id, name, city
`

type CreateAuthorParams struct {
	Name string
	City pgtype.Text
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.City)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.City)
	return i, err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, city FROM authors WHERE id = $1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.City)
	return i, err
}
